services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - GIN_MODE=release
    ports:
      - "8080:8080"
    depends_on:
      - db
    cpu_count: 2
    cpu_shares: 2048
    mem_limit: 4g
  db:
    image: percona:8.0
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      start_period: 5s
      interval: 3s
      timeout: 5s
      retries: 5
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes  # Not a prod configuration
      - MYSQL_DATABASE=urlshortener
      - INIT_ROCKSDB=1
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/my.cnf
    cpu_count: 6
    cpu_shares: 4096
    mem_limit: 32g